### ISSUE TITLE
Plugin no longer works?

### ISSUE THREAD

**Issue by garygulman** [robrichardson13/alch-blocker#21] opened 2024-01-17 06:58 UTC
Have used this plugin for a long time, in the past few weeks it has stopped working completely.

**Comment by zdunbrack-chwy** [comment] 2024-01-18 16:07
are you on transparent mode? likely duplicate of  #19 - I have a PR to fix it but need @robrichardson13 to review and approve #20

**Comment by zdunbrack** [comment] 2024-01-18 16:08
are you on transparent mode? that's a known issue, established in #19. I have a PR #20 to fix it, but I need @robrichardson13's approval to merge in, then will need RL team to review the subsequent plugin-hub PR before it can be fixed.

in the meantime, using "hidden" mode should work.

**Comment by zdunbrack** [comment] 2024-01-23 16:24
if you're on transparent mode, I'll consider this a duplicate of #19 and close it. if you're referring to a different issue, feel free to reopen this thread.
fix will go out with version 1.5 once I make the plugin-hub PR and runelite maintainers review it

**Closed by zdunbrack** 2024-01-23 16:24 UTC
Labels: bug

**Comment by garygulman** [comment] 2024-01-23 16:32
Mine is not working on either setting currently, have uninstalled and reinstalled as well. I have not changed any logic things because I have no idea how lol. Hopefully all is fixed with 1.5

**Comment by zdunbrack** [comment] 2024-01-23 16:44
What's happening with it then? Is it not filtering anything at all? Do you have the plugin enabled? lol
curious what your config is like, but "not working at all" is not something I've been able to reproduce
(screenshots or w/e would be helpful I suppose)

**Comment by garygulman** [comment] 2024-01-23 16:57
![Screenshot 2024-01-23 105446](https://github.com/robrichardson13/alch-blocker/assets/156886493/b428ac00-96cd-4cb0-9600-3f8b9c343033)

It then still alchs it. I do not have instant inventory plugin, but I do have a lot of plugins. Again this worked great for a long time before

**Comment by zdunbrack** [comment] 2024-01-23 17:16
Given that I can't reproduce your issue, there's probably another plugin that it's conflicting with. This is definitely different from the issue I just fixed. What I was seeing is that objects would be filtered, but they wouldn't prevent alching. In your case, though, it's not even visually filtering the objects at all.

I'd suggest the following steps:
1. Create a plugin profile with your current configuration (second category in the plugin tab, between plugin list and plugin hub)
2. Create a new profile for testing so you can easily revert to your preferred configuration
3. Disable every other plugin you can and see if it fixes it

That should help you confirm that it is a plugin conflict of some kind. Then you'll just have to go through the process of turning things on and off until you figure out what the issue is. Because at this point, it really seems like it has to be a plugin conflict. But we should determine that as concretely as we can.

**Comment by garygulman** [comment] 2024-01-23 17:49
THANK YOU! Remaining Casts Plugin
![Screenshot 2024-01-23 113937](https://github.com/robrichardson13/alch-blocker/assets/156886493/edc12cf6-71e3-47c5-a989-0af9eb8e181e)

Checking 'show on menu tooltip' is what seems to break it
Thank you!

**Comment by zdunbrack** [comment] 2024-01-23 18:57
Fascinating - I'll try to take a look at that plugin when I get a chance, can update the README in the meantime to make sure other folks don't hit the same issue. Glad you figured it out! :)

**Comment by kanderson66** [comment] 2024-03-26 15:16
Thanks! Ive been having this issue since OP posted this as well. Gave up on it till I decided to revisit the thread to see if there was a solution- this did the trick!
